# Generated by Django 2.2 on 2022-04-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=15, verbose_name='Имя пользователя')),
                ('name', models.CharField(max_length=15, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=15, verbose_name='Фамилия')),
                ('birthday', models.DateField(blank=True, verbose_name='Дата рождения')),
                ('email', models.EmailField(blank=True, default=None, max_length=254, verbose_name='Адрес электронной почты')),
                ('phone_number', models.CharField(blank=True, default=None, max_length=20, verbose_name='Номер телефона')),
                ('vk_account', models.URLField(blank=True, default=None, verbose_name='Ссылка ВК')),
                ('tg_account', models.CharField(blank=True, default=None, max_length=30, verbose_name='Ссылка Телеграм')),
                ('country', models.CharField(blank=True, default=None, max_length=30, verbose_name='Страна')),
                ('city', models.CharField(blank=True, default=None, max_length=30, verbose_name='Город')),
            ],
            options={
                'db_table': 'profiles_db',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=15, verbose_name='Имя')),
                ('password', models.CharField(max_length=20, verbose_name='Пароль')),
            ],
            options={
                'db_table': 'users_db',
            },
        ),
    ]
