# Generated by Django 3.2.5 on 2022-05-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nick_name',
            field=models.CharField(max_length=15, verbose_name='Имя пользователя'),
        ),
    ]
