# Generated by Django 3.2.5 on 2022-05-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0010_auto_20220506_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.CharField(max_length=2000, null=True, verbose_name='О себе'),
        ),
    ]
