# Generated by Django 3.2.5 on 2022-05-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0012_auto_20220506_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(max_length=30, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(max_length=30, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=15, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tg_account',
            field=models.CharField(max_length=30, verbose_name='Ссылка Телеграм'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vk_account',
            field=models.URLField(verbose_name='Ссылка ВК'),
        ),
    ]
