# Generated by Django 3.2.5 on 2022-05-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0015_auto_20220506_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(default=None, max_length=1000, verbose_name='О себе'),
        ),
    ]
