# Generated by Django 3.2.5 on 2022-05-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0019_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('m', 'Мужчина'), ('f', 'Женщина')], default='m', max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nick_name',
            field=models.CharField(max_length=15, verbose_name='Ник'),
        ),
    ]
